---
title: "Data_Analysis_ctrl"
author: "Soizick and Gicu"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadLib, message=FALSE}
library(mixOmics)
library(metagenomeSeq)
library(reshape2)
```

# Data with sick samples preparation

```{r ,cache=TRUE}
df_abundances <- read.delim("../data/abondances.csv", sep = ",", 
                            stringsAsFactors = FALSE)
```

```{r ,cache=TRUE}
abundances <- df_abundances[ ,grep("A_", colnames(df_abundances))] +
  df_abundances[ ,grep("B_", colnames(df_abundances))]
dim(abundances)
condition <- rep("LBA", ncol(abundances))
condition[grep("EN", colnames(abundances))] <- "EN"
condition <- factor(condition)
table(condition)

id_abundances <- as.character(colnames(abundances))
id_abundances <- sapply(id_abundances, function(ac) 
  substr(ac, nchar(ac) - 19, nchar(ac) - 18))
id_abundances <- gsub("A", "0", id_abundances)
id_abundances <- gsub("N", "0", id_abundances)
table(id_abundances)

species <- sapply(df_abundances[ ,1], function(aname) 
  unlist(strsplit(aname, ";")))
species <- sapply(species, function(avect) {
  find_unknown <- grep("unknown", avect)
  if (length(find_unknown) > 0) {
    return(avect[-find_unknown])
  } else return(avect)
})
species <- unlist(sapply(species, function(avect) avect[length(avect)]))
species <- unname(species)

abundances <- apply(abundances, 2, function(acol) tapply(acol, species, sum))
species <- rownames(abundances)
colnames(abundances) <- paste(condition,id_abundances,sep='_')
```

# Data with control samples preparation

```{r readAbondances_ctrl ,cache=TRUE}
df_abundances_ctrl <- read.delim("../data/abondances-ctrl.csv", sep = ",", 
                            stringsAsFactors = FALSE)
summary(df_abundances_ctrl[ ,1:15])
abundances_ctrl <- df_abundances_ctrl[ ,grep("LBA_|EN_", colnames(df_abundances_ctrl))]
dim(abundances_ctrl)
```

```{r}
condition_ctrl <- rep("LBA", ncol(abundances_ctrl))
condition_ctrl[grep("EN", colnames(abundances_ctrl))] <- "EN"
condition_ctrl <- factor(condition_ctrl)
table(condition_ctrl)
```
```{r}
id_abundances_ctrl=paste(c(1,1,2,2,3,3,4,4,5,5,6,6),condition_ctrl,sep='_')
colnames(abundances_ctrl)=id_abundances_ctrl
```

```{r extractSpecies ,cache=TRUE}
species <- as.data.frame(sapply(df_abundances_ctrl[ ,1], function(aname) 
  unlist(strsplit(aname, ";"))))
species <- sapply(species, function(avect) {
  find_unknown <- grep("unknown", avect)
  if (length(find_unknown) > 0) {
    return(avect[-find_unknown])
  } else return(avect)
})
species <- unlist(sapply(species, function(avect) avect[length(avect)]))
species <- unname(species)
species <- sapply(species,as.character)
```

```{r mergedTaxon ,cache=TRUE}
abundances_ctrl <- apply(abundances_ctrl, 2, function(acol) tapply(acol, species, sum))
species <- rownames(abundances_ctrl)
```

```{r ,cache=TRUE}
df <- data.frame(abundances_ctrl)
names(df) <- paste0("sample", 1:ncol(df))
ggplot(df, aes(x = sample1 +1)) + geom_histogram(bins = 50) + scale_y_log10() +
  theme_bw() + xlab("counts (sample 1)") + ggtitle("Sample 1 distribution in raw data")
```

```{r distLog ,cache=TRUE}
ggplot(df, aes(x = sample1 + 1)) + geom_histogram(bins = 50) +
  theme_bw() + xlab("counts (sample 1)") + scale_x_log10() +
  ggtitle("Sample 1 distribution (log scale)")
```

# Venn Diagram

```{r , eval=FALSE}
library(VennDiagram)
library(png)
```

```{r , cache=TRUE, eval=FALSE}
venn.diagram(list(ctrl=rownames(abundances_ctrl),sick=rownames(abundances)),"Venn.png",imagetype="png")

img <- readPNG("Venn.png")

if(exists("rasterImage")){
      plot(1:5,1:5, type='n',asp = 1, xaxt="n", yaxt="n",ylab='',xlab='',main="Venn Diagram")
      rasterImage(img,0,0,6,6)
}
```

```{r venn, cache=TRUE}
library(gplots)
venn(list(ctrl=rownames(abundances_ctrl),sick=rownames(abundances)))
```

# New data sets with commun bacteria

```{r}
data_commun_sick <- abundances[which(rownames(abundances)%in%rownames(abundances_ctrl)),]
data_commun_ctrl <- abundances_ctrl[which(rownames(abundances_ctrl)%in%rownames(abundances)),]
data_supp <- cbind.data.frame(data_commun_sick,data_commun_ctrl)
```

# PCA

```{r}
log_commun_sick<-log(t(data_commun_sick)+1)
log_commun_ctrl<-log(t(data_commun_ctrl)+1)

clean_condition <- factor(condition[id_abundances != "29"])
clean_id <- factor(id_abundances[id_abundances != "29"])
```


```{r}
pca_raw <- pca(log_commun_sick, ncomp = ncol(data_commun_sick), 
               logratio = 'none')
```

**Adding supplementary individuals**

```{r}
suppIndiv <- log_commun_ctrl%*%pca_raw$rotation[,1:2]
plotIndiv(pca_raw, 
          comp = c(1,2),
          pch = 16, 
          ind.names = FALSE, 
          group=condition,
          col.per.group = color.mixo(1:2),
          legend = TRUE,
          style="graphics",
          title="PCA for log-tranformed data")
points(suppIndiv[,1],suppIndiv[,2],col=ifelse(condition_ctrl=='EN',"dodgerblue2","darkorange"),pch=1,cex=1.5)
```

# PLS-DA

```{r plsda,cache=TRUE}
set.seed(33)
res_plsda <- tune.splsda(log_commun_sick[id_abundances != "29",], clean_condition, 
                         ncomp = nlevels(clean_condition),
                         multilevel = clean_id,
                         test.keepX = 1:20, validation = 'Mfold', folds = 10, 
                         dist = 'mahalanobis.dist', nrepeat = 10,
                         progressBar = FALSE,scale=FALSE)   #ajout de scale=FALSE sinon résultats incohérents

plot(res_plsda)

sel_keepX <- res_plsda$choice.keepX[1:2]
sel_keepX

res_splsda <- splsda(log_commun_sick[id_abundances != "29",], clean_condition, 
                     ncomp = nlevels(clean_condition), multilevel = clean_id,
                     keepX = sel_keepX)

plotIndiv(res_splsda, comp = c(1,2), ind.names = FALSE, ellipse = TRUE, 
          legend = TRUE, title = 'sPLS-DA Comp 1 - 2',style="graphics")
suppIndiv <- log_commun_ctrl%*%res_splsda$loadings$X
points(suppIndiv[,1],suppIndiv[,2],col=ifelse(condition_ctrl=='EN',"dodgerblue2","darkorange"),pch=16,cex=1.5)
```






